### ISSUE TITLE
SLSA verification failed: error searching rekor entries: no matching entries found

### ISSUE THREAD

**Issue by zurrehma** [slsa-framework/slsa-verifier#105]
Hi,
 I have created a Provence for test repo using below workflow.
```
name: SLSA go releaser
on:
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    permissions:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read # To read the workflow path.
    # needs: args
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.0.0
    with:
      go-version: 1.18
```
 However when i verify it using slsa-verifier it give me following error, any hint on this?
```
slsa-verifier % go run main.go -artifact-path ~/Downloads/binary-linux-amd64 -provenance ~/Downloads/binary-linux-amd64.intoto.jsonl -source <source-repo>                
FAILED: SLSA verification failed: error searching rekor entries: no matching entries found
exit status 2
```

**Comment by asraa** [comment]
Hi!

Yes there was an issue in the rekor deployment that caused searching rekor entries to fail.

If you use the v1.1.1 builder and verifier at head, you should be able to verify successfully. Let me know!

**Comment by laurentsimon** [comment]
Note: We are releasing a new version of the verifier later today to avoid this issue

**Comment by laurentsimon** [comment]
[zurrehma](https://github.com/zurrehma) may I ask which repo you were trying it on?

**Comment by zurrehma** [comment]
@laurentsimon For now i am just teesting it on of my test repos.

**Comment by asraa** [comment]
Thanks! Should be working now, happy to check. Use https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.1.1 please!

**Comment by zurrehma** [comment]
yes, that worked. Thanks!
