### ISSUE TITLE
Add generic testsdata for its release

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#133]
We need to populate https://github.com/slsa-framework/slsa-verifier/tree/main/testdata with tests data for the generic builder.
We typically do this as part of https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#update-verifier

It may make sense to create a folder for each builder under each `testsdata/vX.Y.Z`.

Some tests cases may be kinda general while others may be more builder-specific. Or maybe we just duplicate each of these for each builder, this way we're certain everything works.

@asraa Wdut? 

/cc @ianlewis

**Comment by asraa** [comment]
> It may make sense to create a folder for each builder under each testsdata/vX.Y.Z.

+1

> Some tests cases may be kinda general while others may be more builder-specific.

Yes, right. For things like rekor errors we can keep them at the top-level for testdata/. Some things are general, e.g. checking builder pinning, but those can also be duped for each builder.

So the structure could be
```
testdata/
   - general tests
   go/
     v1.0.0/
     v1.1.1/
     general go tests
   generic/
      v1.0.0/
      general generic tests
```

**Comment by laurentsimon** [comment]
LGTM. Let's also document the workflows (in example-package) to use to generate these... maybe they can all be in the same (that's a detail, I'm just curious :))?

**Comment by ianlewis** [comment]
@asraa Do we still need to do anything for this issue? or can it be closed?

This issue is the last task referenced by https://github.com/slsa-framework/slsa-github-generator/issues/544 and I think we'd like to get that closed.
