### ISSUE TITLE
Verification failure for release v1.1.1

### ISSUE THREAD

**Issue by naveensrinivasan** [slsa-framework/slsa-verifier#144]
- I downloaded the release binary slsa-verifier-linux-amd64 and provenance slsa-verifier-linux-amd64.intoto.jsonl `v1.1.1`.
- Followed the instructions to verify `go run . -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.1.1 -branch release/v1.1.1`
- It fails 
```
Verified against tlog entry 2907428
verified signature on SLSA provenance produced at
 {
	"caller": "slsa-framework/slsa-verifier",
	"commit": "eea3a5d3af9370a6a35946fa24e47a426c3f4576",
	"job_workflow_ref": "/slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@refs/tags/v0.0.1",
	"trigger": "push",
	"issuer": "https://token.actions.githubusercontent.com"
}
verification failed: expected branch 'refs/heads/release/v1.1.1', got 'refs/heads/release/v1.0': branch used to generate the binary does not match provenance
exit status 2
```

**Comment by asraa** [comment]
Added the instructions in the release notes. I'll update the README.md to mention that releases from now on will be made on a release branch.

**Comment by naveensrinivasan** [comment]
>go run . -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.0.1 -branch release/v1.0

This works.

Thanks, the README needs to be fixed. 

All of this has to be automated :)

**Comment by asraa** [comment]
what part would need to be updated? maybe verification instructions for each release? feel free to open an issue
