### ISSUE TITLE
Verify cert info vs provenance content

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#157]
To harden the verification we should very that information in the cert is consistent with information in the provenance, such as:
- commit hash of source repo
- repository name of source repo
- builderID
- entryPoint
- other info contained in both cert and provenance 

This would mitigate problems like https://github.com/slsa-framework/slsa-github-generator/pull/598

/cc @asraa

**Comment by laurentsimon** [comment]
We also need to verify that no other claims exist. Example: `"parameters"` should be empty, vars should be empty; no additional env variables exists, metadata is correct, etc. Here's an example of the provenance text:
```json
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "subject": [
    {
      "name": "pkg:npm/%40ps-testing/dummy-provenance@1.0.0-4609437881.1",
      "digest": {
        "sha512": "7bf3802638cdb9a6a64d6342ef6f65986ab9d79b1fdb3456f720f62cfcf56220620563e19817ff134b57ba9cfd1e6ed65751d485fa0dbcd613ee845509c03ab3"
      }
    }
  ],
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "predicate": {
    "buildType": "https://github.com/npm/cli/gha/v2",
    "builder": {
      "id": "https://github.com/actions/runner"
    },
    "invocation": {
      "configSource": {
        "uri": "git+https://github.com/npm/provenance-tests@refs/heads/main",
        "digest": {
          "sha1": "b8adf0e2ea663818674b0b542364638d016256d9"
        },
        "entryPoint": ".github/workflows/publish-with-provenance.yml"
      },
      "parameters": {},
      "environment": {
        "GITHUB_EVENT_NAME": "workflow_dispatch",
        "GITHUB_REF": "refs/heads/main",
        "GITHUB_REPOSITORY": "npm/provenance-tests",
        "GITHUB_REPOSITORY_ID": "566758891",
        "GITHUB_REPOSITORY_OWNER_ID": "6078720",
        "GITHUB_RUN_ATTEMPT": "1",
        "GITHUB_RUN_ID": "4609437881",
        "GITHUB_SHA": "b8adf0e2ea663818674b0b542364638d016256d9",
        "GITHUB_WORKFLOW_REF": "npm/provenance-tests/.github/workflows/publish-with-provenance.yml@refs/heads/main",
        "GITHUB_WORKFLOW_SHA": "b8adf0e2ea663818674b0b542364638d016256d9"
      }
    },
    "metadata": {
      "buildInvocationId": "4609437881-1",
      "completeness": {
        "parameters": false,
        "environment": false,
        "materials": false
      },
      "reproducible": false
    },
    "materials": [
      {
        "uri": "git+https://github.com/npm/provenance-tests@refs/heads/main",
        "digest": {
          "sha1": "b8adf0e2ea663818674b0b542364638d016256d9"
        }
      }
    ]
  }
}

```

**Comment by ianlewis** [comment]
> We also need to verify that no other claims exist. Example: `"parameters"` should be empty, vars should be empty; no additional env variables exists, metadata is correct, etc. Here's an example of the provenance text:

Is this something we should do for just `npm publish`? or for other builders as well?

**Comment by laurentsimon** [comment]
I think starting with npm publish should be enough for now. You're right we could extend this to our own builders in the future, but probably low priority?

**Comment by ianlewis** [comment]
> I think starting with npm publish should be enough for now. You're right we could extend this to our own builders in the future, but probably low priority?

Agreed. This is more important with the forgeable provenance content of `npm publish`.

**Comment by ianlewis** [comment]
Laurent thinks this is done.
