### ISSUE TITLE
Feature: rename repo/tool to expand scope

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#16]
`slsa-verifier` as a repo/CLI name means the tool is used to verify slsa provenance. However, in some scenarios, a developer may want to inspect the provenance. So it may be beneficial to change the repo name to some more generic like `slsa-provenance` and broaden the scope of the tool:

1. `verify` command to verify the provenance
2. `inspect` command to inspect the provenance
3.  _somethingelse_

Thoughts?

cc @joshuagl @MarkLodato @asraa

**Comment by joshuagl** [comment]
I like this.

I've got some ugly local hacks for inspection when I've been testing changes and wanting to see the predicate in a generated jsonl file.

**Comment by MarkLodato** [comment]
Personally I'd keep the name, but if you want something more generic, maybe "slsa-tool"?

**Comment by laurentsimon** [comment]
Let's keep this PR open to see what others think. "slsa-tool" may also mean it can generate provenance, which may be feasible if we merge the code with the API/CLI being developed in https://github.com/slsa-framework/slsa-github-generator/pulls /cc @[ianlewis](https://github.com/ianlewis)
