### ISSUE TITLE
Update comments for actions / renovatebot

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#169]
We use `# tag=v3` in many actions. Removatebot is unable to display the version a PR updates to, and I'm nott sure renovatebot even updates to a released version. For example https://github.com/slsa-framework/slsa-verifier/pull/165 updates codeql action with a hash that is *not* a release.

We need to use `# tag=v3.2.1` instead it seems.

**Comment by laurentsimon** [comment]
@rarkins is this intended behavior?

**Comment by rarkins** [comment]
When tag=v3 it means Renovate will submit a PR whenever the SHA which v3 tag points to changes. So it's not really "updating a version". It's updating a tag's SHA. When the v3 tag is updated, there's no guarantee that any v3.x.y tag points to the same SHA, although that's usually the case.

If using a fully specified tag such as tag=v3.2.1 it means Renovate will instead look for new tags (such as v3.2.2 or v3.3.0) and the update to those. In such a case the PR will clearly state which version is being updated to, along with the SHA update.

As you're no doubt aware, tags are not immutable - as demonstrated by the use of v3 tag in this example - so even a tag=v3.2.1 could experience a SHA-only update, although that hopefully doesn't happen.

**Comment by laurentsimon** [comment]
Thank you for the detailed explanation. I thought `@v3` tag meant the GHA would resolve to the latest tag in v3, e.g., v3.2.1, etc. But from what you're saying that's not how GHA are resolved by GH either.

Would it be possible for renovatebot to indicate the version in the PR description? For example, instead of only having `abcd -> efgch`, something like `(v3) abcd -> efgch`; or, in cases where a v3.x.y corresponds to the v3 tag, `v3.xy -> v3.x.w`. 

Would that break something?

**Comment by rarkins** [comment]
Yes, it should be possible to include the tag in the PR title using some config changes. Please create a discussion in the GitHub repo to try to work out if we can do that using existing config options.

**Comment by laurentsimon** [comment]
Thank you, done https://github.com/renovatebot/renovate/discussions/16818

**Comment by ianlewis** [comment]
Renovate supports comments without the `tag=` bit so I think this issue is solved.
