### ISSUE TITLE
Attestation of 2 artifacts is considered valid even if only one is passed

### ISSUE THREAD

**Issue by mihaimaruseac** [slsa-framework/slsa-verifier#174]
```
mihaimaruseac@ankh:/tmp$ ~/go/bin/slsa-verifier -provenance attestation.intoto.jsonl -source mihaimaruseac/slsa-lvl3-generic-provenance-with-bazel-example -artifact-path fib -artifact-path hello
Verified signature against tlog entry index 3026659 at URL: https://rekor.sigstore.dev/api/v1/log/entries/b7d5d52dfc795dddf1c03e901e96c3cb1803c9f1ecc250a13299131b2564c422
Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.0 at commit e9b5431bcfb0df5d8b2ee622bde8ec4fad9d71d3
PASSED: Verified SLSA provenance
```

Getting the same result if passing only `fib` or `hello` arguments.

I could look into this.

**Comment by laurentsimon** [comment]
> ```
> mihaimaruseac@ankh:/tmp$ ~/go/bin/slsa-verifier -provenance attestation.intoto.jsonl -source mihaimaruseac/slsa-lvl3-generic-provenance-with-bazel-example -artifact-path fib -artifact-path hello
> Verified signature against tlog entry index 3026659 at URL: https://rekor.sigstore.dev/api/v1/log/entries/b7d5d52dfc795dddf1c03e901e96c3cb1803c9f1ecc250a13299131b2564c422
> Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.0 at commit e9b5431bcfb0df5d8b2ee622bde8ec4fad9d71d3
> PASSED: Verified SLSA provenance
> ```
> 
> Getting the same result if passing only `fib` or `hello` arguments.

we did not intend to support multiple `-artifact-path`, but it could be a new feature . https://github.com/slsa-framework/slsa-verifier/issues/91 is related.

> I could look into this.

Awesome, assigned to you

**Comment by mihaimaruseac** [comment]
Moving this to #91 as it contains all possible scenarios and relevant discussion
