### ISSUE TITLE
Allow verification of builderID including the tag

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#189]
Current code only allows matching on `builderID: som/path/to/builder`. This is a simplification that works for our GH native builders, since different version have the same guarantees (level 3). We need to update this behavior to allow users to match o the full id, including tag:
1. Useful if there's a bug
2. useful for GCB where the tag indicates the level.

For GHA, we'll allow both with and without tag. For GCB, we will only allow with tag.

**Comment by laurentsimon** [comment]
Once this is done, we also need corresponding e2e tests

**Comment by asraa** [comment]
@laurentsimon is this done?

**Comment by laurentsimon** [comment]
iirc, not the end-to-end test. Let me do that today

**Comment by laurentsimon** [comment]
Done. Closing.
