### ISSUE TITLE
Annotated git tags don't verify properly

### ISSUE THREAD

**Issue by sethmlarson** [slsa-framework/slsa-verifier#193]
Using slsa-verifier v1.2.0. Annotated git tags (ie those created via `git tag -a X`) don't work with SLSA currently. I have an [example project](https://github.com/sethmlarson/python-slsa-release-test) with three tags, one created annotated (0.1.9), one created "lightweight" (0.1.10), and one created through the GitHub UI (0.1.11, results in a lightweight tag):

```bash
$ git cat-file -t 0.1.9
tag
$ git cat-file -t 0.1.10
commit
$ git cat-file -t 0.1.11
commit
```

The attestation and tarball is attached for each of the three tags. The `.intoto.jsonl` files have been renamed to `.txt` so GitHub doesn't reject them based on the file type. When verifying the attestation against the tarball the lightweight git tags work but the annotated git tag doesn't work.

```bash
$ ./slsa-verifier-linux-amd64 \
  -provenance 0.1.9.intoto.jsonl \
  -artifact-path 0.1.9.tar.gz \
  -tag 0.1.9 \
  -source github.com/sethmlarson/python-slsa-release-test 

Verified signature against tlog entry index 3119376 at URL: https://rekor.sigstore.dev/api/v1/log/entries/d834c415a48108cc7dbfe8a5b295999c94e842f4b4d6f2c078aa334db0ba5cc3
FAILED: SLSA verification failed: invalid DSSE envelope payload: environment type string

$ ./slsa-verifier-linux-amd64 \
  -provenance 0.1.10.intoto.jsonl \
  -artifact-path 0.1.10.tar.gz \
  -tag 0.1.10 \
  -source github.com/sethmlarson/python-slsa-release-test 

Verified signature against tlog entry index 3121002 at URL: https://rekor.sigstore.dev/api/v1/log/entries/609aec4886e378f2159ff9c30e01fb9499d34a4a21848175cdf4b7b491e10293
Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.0 at commit c8f8996e40ef7e0539d0b0ad405cf3abdbd20865
PASSED: Verified SLSA provenance

$ ./slsa-verifier-linux-amd64 \
  -provenance 0.1.11.intoto.jsonl \
  -artifact-path 0.1.11.tar.gz \
  -tag 0.1.11 \
  -source github.com/sethmlarson/python-slsa-release-test 

Verified signature against tlog entry index 3121111 at URL: https://rekor.sigstore.dev/api/v1/log/entries/811167b5a8d9a08c36dd6c8249564d8f4dd806bcf51ed0e23e425a5d0fa33d96
Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.0 at commit c8f8996e40ef7e0539d0b0ad405cf3abdbd20865
PASSED: Verified SLSA provenance
```

[0.1.9.tar.gz](https://github.com/slsa-framework/slsa-verifier/files/9271415/0.1.9.tar.gz)
[0.1.9.txt](https://github.com/slsa-framework/slsa-verifier/files/9271416/0.1.9.txt)
[0.1.10.tar.gz](https://github.com/slsa-framework/slsa-verifier/files/9271417/0.1.10.tar.gz)
[0.1.10.txt](https://github.com/slsa-framework/slsa-verifier/files/9271418/0.1.10.txt)
[0.1.11.tar.gz](https://github.com/slsa-framework/slsa-verifier/files/9271419/0.1.11.tar.gz)
[0.1.11.txt](https://github.com/slsa-framework/slsa-verifier/files/9271420/0.1.11.txt)

**Comment by laurentsimon** [comment]
Thanks for the report!

The verifier is unable to verify the branch. The branch is not in the provenance:
```yaml
"github_base_ref": "",
          "base_ref": null,
```

I'm curious if this problem also occurs if you change your workflow to the following trigger instead https://github.com/actions/starter-workflows/blob/main/ci/go-ossf-slsa3-publish.yml#L17-L18
```yaml
on:
  release:
    types: [created]
```

I suspect that does not work because you're not releasing, just pushing a tag?

**Comment by sethmlarson** [comment]
Yeah this is only when using `on: tag: ...` instead of releases. We use tags on urllib3/urllib3 to initiate the release process and the GitHub release itself comes later.

**Comment by laurentsimon** [comment]
We're limited by the GH's context / payload for verification. Is there's a way to pass a branch option to the git command?

**Comment by sethmlarson** [comment]
So I poked around and discovered that GitHub's `event.base_ref` field can't be relied on to get the branch name *even for lightweight git tags*. It's only consistent when the tag occurs on the same commit as the branch is pointing to which isn't guaranteed.

I verified this is the case using [this repository](https://github.com/sethmlarson/github-action-tag-context-test). I have 3 tags all pointing to the same commit, one lightweight on the branch head (0.7.0), one annotated on the branch head (0.8.0), and one lightweight *after the branch had additional commits added* (0.9.0). Only 0.7.0 was able to verify properly.

```bash
$ ./slsa-verifier-linux-amd64 -artifact-path blob.txt -source github.com/sethmlarson/github-action-tag-context-test -provenance 0.7.0.intoto.jsonl -tag 0.7.0
Verified signature against tlog entry index 3124293 at URL: https://rekor.sigstore.dev/api/v1/log/entries/5396993bd899cd6ef7384c23952030fdc77bf58f9e0898561e8186c94ce01022
Verified build using builder https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.0 at commit 9d4120ca364d63609dd93c7aa75cb642d4da72c4
PASSED: Verified SLSA provenance

$ ./slsa-verifier-linux-amd64 -artifact-path blob.txt -source github.com/sethmlarson/github-action-tag-context-test -provenance 0.8.0.intoto.jsonl -tag 0.8.0
Verified signature against tlog entry index 3124292 at URL: https://rekor.sigstore.dev/api/v1/log/entries/0a2e8967e3cd5f5a49fe708d8ec08787ff32978b1c0fe4157eb4401208053845
FAILED: SLSA verification failed: invalid DSSE envelope payload: environment type string

$ ./slsa-verifier-linux-amd64 -artifact-path blob.txt -source github.com/sethmlarson/github-action-tag-context-test -provenance 0.9.0.intoto.jsonl -tag 0.9.0
Verified signature against tlog entry index 3124298 at URL: https://rekor.sigstore.dev/api/v1/log/entries/e35449c1088d188eacb3202cb41b1c453d6fc026d87eb7fad116320308d11a94
FAILED: SLSA verification failed: expected branch 'refs/heads/main', got 'refs/tags/0.7.0': branch used to generate the binary does not match provenance
```

Investigating the value saved for `predicate.invocation.environment.github_event_payload.base_ref` for each of the attestation files we find these values:

- 0.7.0: `"refs/heads/main"`
- 0.8.0: `null`
- 0.9.0: `"refs/tags/0.7.0"`

I suspect if there was no tag on the commit for 0.9.0 it would have been `null` as well.

Here are the files you can use to verify this issue (.intoto.jsonl renamed to .txt):

- [0.7.0.txt](https://github.com/slsa-framework/slsa-verifier/files/9275294/0.7.0.txt)
- [0.8.0.txt](https://github.com/slsa-framework/slsa-verifier/files/9275295/0.8.0.txt)
- [0.9.0.txt](https://github.com/slsa-framework/slsa-verifier/files/9275296/0.9.0.txt)
- [blob.txt](https://github.com/slsa-framework/slsa-verifier/files/9275297/blob.txt)

**Comment by laurentsimon** [comment]
Thanks for the thorough analysis, @sethmlarson 

The original motivation for verifying the branch was that the branch is typically protected, whereas the others are not.
SLSA has a dedicated "source requirement" for this, so branch need not be verified. I was hoping we could, but your investigation shows it does not work well.

I suggest we make branch verification optional, like we do for the tag.

I can update https://github.com/slsa-framework/slsa-verifier/pull/192 with the suggested change.

@ianlewis @asraa any objection to the change?

**Comment by sethmlarson** [comment]
Another question is "should branch and tag verification be allowed together?" This strange behavior of "sometimes working sometimes not" seems like a footgun that users might run into causing confusion around false negatives.

**Comment by asraa** [comment]
> I suggest we make branch verification optional, like we do for the tag.

+1, see below

> "should branch and tag verification be allowed together?

Perhaps: I think we can have a one of Source pinning option: either branch, tag, or commit (worst case)?

**Comment by laurentsimon** [comment]
> > I suggest we make branch verification optional, like we do for the tag.
> 
> +1, see below
> 
> > "should branch and tag verification be allowed together?

Is there value letting users / maintainers decide? Or do you think we should unilaterally not allow them together?

> Perhaps: I think we can have a one of Source pinning option: either branch, tag, or commit (worst case)?

I was thinking of something like that too. It's not clear what branch gives you. 

I'm starting to think we should leave it up to users decide how they want to verify, since it depends on use case / scenario. I see it as a "contract" between repo maintainers and their users. In some cases, branch and tag will work; in other they won't... maybe we should leave it up to repo maintainers / policy writers to decide.

It's not ideal, but we're still providing all the knobs for user to extract the relevant information. For more security, they need to have the 2LGTM source requirements.


> 
> Edit: not sure how to reconcile the user experience. In the annotated tag, the `github_ref` is `refs/tag/TAG`. Users should not pass this in as tag, but rather as branch for it to work here.
> 
> Or maybe `-tag TAG` also searches for `github_ref` as `refs/tags/TAG` internally.

I'm worried we introduce additional complexity and we're not sure if this may be confusing to users.

**Comment by laurentsimon** [comment]
> Or maybe -tag TAG also searches for github_ref as refs/tags/TAG internally.

We already do that. So I think we just need to make the branch optional. We can add some warning that verifying the branch is not reliable due to the way git works...

**Comment by laurentsimon** [comment]
Merged in https://github.com/slsa-framework/slsa-verifier/pull/192.
Need to add e2e tests.

**Comment by laurentsimon** [comment]
Added e2e tests in https://github.com/slsa-framework/example-package/blob/7d1423ae12ab7c4aed93d5e562d5939da42ffca2/.github/workflows/e2e.generic.tag.main.annotated.slsa3.yml

**Comment by laurentsimon** [comment]
Added e2e tests https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.tag.main.annotated.slsa3.yml
