### ISSUE TITLE
Comments from @sethmlarson

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#200]
https://gist.github.com/sethmlarson/b933cbc6970b81e9069d2da4c16089ce

This is mostly around tags https://github.com/slsa-framework/slsa-verifier/issues/193.

- [x] https://github.com/ossf/scorecard/pull/2131
- [x] https://github.com/slsa-framework/slsa-verifier/pull/192

Thanks @sethmlarson for writing this up.

**Comment by sethmlarson** [comment]
I think this issue can be closed now! :rocket:

**Comment by laurentsimon** [comment]
Thank you, closing.
