### ISSUE TITLE
Create an argument to verify workflow_dispatch input arguments

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#213]
`--workflow_dispatch release_version=v1.2.0, whatever=value` OR
`--workflow-dispatch release_version=v1.2.0, whatever=value` OR
`--workflow-inputs release_version=v1.2.0, whatever=value` OR
`--workflow-input release_version=v1.2.0 --workflow-input whatever=value`

@asraa @ianlewis Wdut? This came up for https://github.com/GoogleContainerTools/jib/blob/master/.github/workflows/jib-cli-release.yml

**Comment by laurentsimon** [comment]
repository documentation to update:
- [ ] https://github.com/GoogleContainerTools/jib/blob/master/jib-cli/README.md

**Comment by laurentsimon** [comment]
Closed by https://github.com/slsa-framework/slsa-verifier/pull/216.

**Comment by laurentsimon** [comment]
Re-opening due to missing e2e tests

**Comment by asraa** [comment]
e2e testing added here https://github.com/slsa-framework/example-package/pull/96 for container, go, and generic
