### ISSUE TITLE
Feature: CLI unit tests

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#26]
Add unit tests that check every possible error output from the CLI (rekor error, signature missing, signature verification error, etc).

I think these will be re-usable even once we adopt the provenance changes from https://github.com/slsa-framework/slsa-github-generator

I did this for tag, branch, versioned-tag and source in https://github.com/slsa-framework/slsa-verifier/pull/23

**Comment by laurentsimon** [comment]
We should also verify that verification works for the head of slsa-github-generator-go and for any version of the generator released

**Comment by asraa** [comment]
This is complete now.
