### ISSUE TITLE
Clarifying some details of signature verification

### ISSUE THREAD

**Issue by rbehjati** [slsa-framework/slsa-verifier#395]
The SLSA provenance specification (https://slsa.dev/provenance/v0.2) states that 

> Consumers MUST accept only specific (signer, builder) pairs. For example, “GitHub” can sign provenance for the “GitHub Actions” builder, and “Google” can sign provenance for the “Google Cloud Build” builder, but “GitHub” cannot sign for the “Google Cloud Build” builder.

I wonder if this is enforced/verified by slsa-verifier. A related attack scenario that we in Oak are interested in preventing is as follows: Let's say that an attacker takes a provenance generated by the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md), modifies some parts of it, and somehow signs it (perhaps by writing a GitHub action that signs provenances). Can this be detected by slsa-verifier? In particular, can it be detected that the signer is not the associated with the GitHub trusted builder (i.e., `https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.1`)?

Sorry if this is already described somewhere, and I've missed.

**Comment by laurentsimon** [comment]
You're correct. The slsa-verifier detects this. For GitHub-generated provenance, we verify the builder identity https://github.com/slsa-framework/slsa-verifier/blob/main/verifiers/internal/gha/builder.go#L22-L29

For GCB, we verify the signing key is from one of the GCB keys: https://github.com/slsa-framework/slsa-verifier/tree/main/verifiers/internal/gcb/keys/materials

Feel free to suggest some documentation update if you think it's needed. Otherwise, feel free to close the issue.

**Comment by ianlewis** [comment]
> Let's say that an attacker takes a provenance generated by the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md), modifies some parts of it, and somehow signs it (perhaps by writing a GitHub action that signs provenances).

Reusable workflows have their own identity for the purposes of signing, so without calling our workflow they wouldn't be able to sign the provenance in a way that the verifier would accept.

> You're correct. The slsa-verifier detects this. For GitHub-generated provenance, we verify the builder identity https://github.com/slsa-framework/slsa-verifier/blob/main/verifiers/internal/gha/builder.go#L22-L29

I'll just clarify that, the attacker could call the `slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml` workflow in their repo and generate provenance with our builder ID and signed by our workflow but the provenance would indicate that the artifacts were built by a workflow run triggered by *their* repo, and that the top-level workflow was their workflow. And they wouldn't be able to freely modify any of the provenance fields.

So they can do one or the other of the following but can't do both:
1. Generate provenance that uses the `https://github.com/slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@refs/tags/v1.2.1` builder ID and have a verifiable signature.
2. Generate provenance where the source is the Oak repo/workflow.

As @laurentsimon mentioned, the `slsa-verifier` verifies both so it would catch this.

**Comment by rbehjati** [comment]
Thanks for clarifying. This was very helpful. 
@tiziano88 Do you have any additional comment?

**Comment by asraa** [comment]
> Reusable workflows have their own identity for the purposes of signing, so without calling our workflow they wouldn't be able to sign the provenance in a way that the verifier would accept.

Agree -- just for picture purposes, the signing certificate issued by Fulcio looks like this:
![cert](https://user-images.githubusercontent.com/5194569/206743379-a9dfdd64-5db0-4371-886f-2b13d0c741ae.svg)

The SAN of the cert is the slsa-framework trusted builder, which means that if the attacker wanted to insert any malicious items into the signed provenance they would need to:
(1) Insert malicious code into our builder. The builder is fully qualified with ref, so they MUST be inserting a malicious commit into our slsa-framework/slsa-github-generator repository. We do have branch protection and reviews enabled (check through scorecard!) and we hope that we have additional protection by being an open source repository where poeple can audit the source.
(2) They can compromise the signing certificate authority or the trust roots that the slsa-verifier uses to verify the certificate chain. We use Sigstore's public signing CA and integrate their public trust root built on TUF (available at github.com/sigstore/root-signing), so we can also monitor any root malfeasance there.

**Comment by rbehjati** [comment]
Thanks for the clear description Asra :) I'll close the issue.

**Comment by ianlewis** [comment]
> We do have branch protection and reviews enabled (check through scorecard!)

Well, we can't promise you can check this via scorecard bc we don't give it the PAT that it needs to do this check because it would give the action too many permissions. For now you'll have to just trust us that we have a '*' branch projection rule that requires reviews.

**Comment by laurentsimon** [comment]
You can run scorecard manually with your own token, and you'll be able to access to branch protection settings. Not ideal. I'll create a scorecard issue, because that's something that needs to be fixed
