### ISSUE TITLE
Enable pre-built binary releases with GoReleaser

### ISSUE THREAD

**Issue by aalmiray** [slsa-framework/slsa-verifier#397]
[GoReleaser](https://goreleaser.com/) simplifies creating Git releases and posting binaries as release assets and to package managers such as Homebrew.

Consider posting pre-built binaries for multiple platforms (not just linux-amd64 as it is at the moment).

cc: @goreleaser @caarlos0

**Comment by ianlewis** [comment]
Thanks. We currently use our own [builder workflow](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/go)  which has configuration that is similar to GoReleaser. We could definitely generate binaries for multiple architectures (though I'm not sure about homebrew).

**Comment by aalmiray** [comment]
GoReleaser usually builds the binaries for you and the posts them to several package managers. However, I believe it's possible to skip the build step (so that you may keep your own build process for security reasons) and instruct GoReleaser to continue with packaging and releasing options.

**Comment by suzuki-shunsuke** [comment]
[google/osv-scanner](https://github.com/google/osv-scanner) and [aquaproj/aqua](https://github.com/aquaproj/aqua) build binaries with Goreleaser and generate SLSA Provenance with [slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md).

- https://github.com/google/osv-scanner/blob/124ad0e2311dc8f25cec2aa298e467a7fffef3b1/.github/workflows/goreleaser.yml#L28-L53
- https://github.com/aquaproj/aqua/blob/c4660ab22920a21dcc7dc0ccdc8947e15ac38c6f/.github/workflows/release.yaml#L38-L81

These workflows may be useful for this issue.

**Comment by suzuki-shunsuke** [comment]
I've created a pull request.
- https://github.com/slsa-framework/slsa-verifier/pull/421

**Comment by suzuki-shunsuke** [comment]
https://github.com/slsa-framework/slsa-verifier/pull/434 was merged.
Pre built binaries for each platform (windows, linux, macOS / amd64, arm64) will be released from the next release.

**Comment by aalmiray** [comment]
This are amazing news and an excellent way to begin the new year! 🙏 @suzuki-shunsuke!

**Comment by laurentsimon** [comment]
Multiple releases done in https://github.com/slsa-framework/slsa-verifier/pull/434, thanks you @suzuki-shunsuke 
Closing the issue

**Comment by suzuki-shunsuke** [comment]
v2.1.0 has been released. 🎉 
https://github.com/slsa-framework/slsa-verifier/releases/tag/v2.1.0
