### ISSUE TITLE
bug: Token does not have permissions to read releases

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#405]
See https://github.com/slsa-framework/slsa-verifier/actions/runs/3690939607/jobs/6248473358: `gh: Bad credentials (HTTP 401)`

The default `GITHUB_TOKEN` may work for the API call. Otherwise let's use a fine-grained token.
We still want the existing token to create issues, but we could also update it to a fine-grained token.

**Comment by ianlewis** [comment]
I think we just need to set the `GITHUB_TOKEN` env var there.
https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows

**Comment by laurentsimon** [comment]
turns out we don't need the PAT to create issues on our own repos. We can re-use the GITHUB_TOKEN and set the `issues: write` permissions.

**Comment by ianlewis** [comment]
> turns out we don't need the PAT to create issues on our own repos. We can re-use the GITHUB_TOKEN and set the `issues: write` permissions.

I think this is true if it's the same repo but in our case we are using a GITHUB_TOKEN from example-package to write issues to slsa-github-generator and slsa-verifier repos.

**Comment by ianlewis** [comment]
ah, this is the pre-submit in this repo so yeah `issues: write` should work.
