### ISSUE TITLE
[feature] API with content instead of files

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#475]
Consumers of our API may want to keep provenance and artifact in memory (e.g., when downloaded from npm urls) for performance reasons.

So we should of think exposing an API that can take as input `byte[]` for arguments that currently use a path to the filesystem. 

NOTE: This is not needed for the CLI, I think

**Comment by ianlewis** [comment]
I think it makes sense for a generalized API to take `[]byte`. I'm pretty sure we don't need to use the filename itself or any file metadata in the validation process. right?

**Comment by asraa** [comment]
That's currently the case (using byte) with the verifiers API: https://github.com/slsa-framework/slsa-verifier/blob/13b4c3e75b2452cccd708bf128ea966d8f758b14/verifiers/verifier.go#L52

But I'm not totally sure which API surface you're intending -- the more granular ones are in the internal pkg.

**Comment by laurentsimon** [comment]
Good point. I recall that we talked about re-factoring the API to look like the CLI with an `options` package, in which case we'd need to expose the `[]byte` API as well. Looks like we need to discuss whether the re-factoring is needed at all.

**Comment by ianlewis** [comment]
Yeah, I imagined at some point updating the internal API to expose a more request/response style API (even if we don't make it a networked service).

I envisioned something like
```golang
type VerifyAttestationRequest struct {
   // ...
}

type VerifyAttestationResponse struct {
   // ...
}

type SLSAVerificationService interface {
    VerifyAttestation(r *VerifyAttestationRequest) (*VerifyAttestationResponse, error)
    // More methods? maybe offline is a separate method?
}
```

I think the main reason we might change it is to simplify ongoing maintenance of the API since we'll have more consumers, but probably it's not strictly needed from a functionality standpoint.

**Comment by laurentsimon** [comment]
Closing this issue since we already have API taking in bytes.
