### ISSUE TITLE
[e2e cli] Add all builders to e2e cli

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-verifier#514]
The e2e-cli script https://github.com/slsa-framework/slsa-verifier/blob/main/.github/workflows/scripts/e2e-cli.sh

runs the slsa-verifier CLI at main against existing provenance formats, in order to catch cases where the CLI may have been broken (since our main_regression_test.go uses the Go API).

We should add all builders to this (along with pulling example-package artifacts directly)

@laurentsimon

**Comment by ramonpetgrave64** [comment]
As of ~August 2023 there are e2e tests for all the builders.
 - https://github.com/slsa-framework/example-package/tree/6737d75f52c37227cbf06f7efb73dc3da8556eba/e2e
