### ISSUE TITLE
feat: remove support for special handling of material verification for npm

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#524]
See https://github.com/slsa-framework/slsa-verifier/pull/521#discussion_r1131610475

**Comment by ianlewis** [comment]
I suppose we may want to be able to verify provenance generated during the public beta. So maybe we can check if it's been generated as of a certain date so that we can check this for provenance generated after the GA?

**Comment by laurentsimon** [comment]
This should work, good idea.

**Comment by asraa** [comment]
Or maybe there's a versioning in their buildType or something else to identify stable format?

**Comment by ianlewis** [comment]
> Or maybe there's a versioning in their buildType or something else to identify stable format?

That's maybe an even better idea.

**Comment by laurentsimon** [comment]
Last time we talk they did not have, ie it was tied to the CLI version. But I think they will change that, so need to follow-up

**Comment by ianlewis** [comment]
This will get fixed by #641

**Comment by ramonpetgrave64** [comment]
#641 is merged.
