### ISSUE TITLE
[npm] Verify publish attestations from npm package signing keys

### ISSUE THREAD

**Issue by asraa** [slsa-framework/slsa-verifier#547]
The npm package signing key will be distributed through Sigstore's TUF root as of next week.

The target will be found at `registry.npmjs.org/keys.json` and has a format like this:https://raw.githubusercontent.com/sigstore/root-signing/f3ebf7f951e021d2b1ad94735d33af7f7834793f/repository/staged/targets/registry.npmjs.org/keys.json

where there is a signatures key and an attestations key.

To get this file in bytes, you can use the sigstore/sigstore TUF client like this:
```
	tufClient, err := tuf.NewFromEnv(context.Background())
	if err != nil {
		check(err)
	}
       keysFileBytes, err := tufClient.GetTarget(registry.npmjs.org/keys.json)
	if err != nil {
		check(err)
	}
```

The format of this file is defined loosely from the protobufs, at least the PublicKeys are from this [proto](https://github.com/sigstore/protobuf-specs/blob/c8a23a43dc1c685d336d112864ba237a15061c53/protos/sigstore_common.proto#L100)

**Comment by laurentsimon** [comment]
Thanks @asraa 

So this is for the provenance signing, correct? Or the publish attestation?

In terms of backward compatibility, does this mean we can drop support for previously-generated attestations entirely?

**Comment by asraa** [comment]
This is the publish attestation - the provenance signing is still always happening with GitHub OIDC.

**Comment by asraa** [comment]
Ah! Clarified offline - the keys in the tuf root are the same as the ones that were hard-coded

https://github.com/slsa-framework/slsa-verifier/blob/b01cb9d69cb87adbd1491f55ff9e54b399ed560d/verifiers/internal/gha/npm.go#L29

So it will be compatible :)

**Comment by ianlewis** [comment]
This is needed by the time npm updates their cert
