### ISSUE TITLE
Malformed Tag version is causing Dependabot to fail

### ISSUE THREAD

**Issue by IAreKyleW00t** [slsa-framework/slsa-verifier#548]
The tag `v1.0.5.-rc.2` (note the extra period) is causing Dependabot to fail due to a Malformed version number, which causes all updates for this Action to fail entirely. It seems like this is the only tag like this, so I suspect it may have been a mistake.

Snippet from Dependabot log:
```
...
updater | 2023/03/31 01:40:08 ERROR <job_636476188> Error processing slsa-framework/slsa-verifier (ArgumentError)
updater | 2023/03/31 01:40:08 ERROR <job_636476188> Malformed version number string 1.0.5.-rc.2
...
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +----------------------------------------------+
updater | |        Dependencies failed to update         |
updater | +------------------------------+---------------+
updater | | slsa-framework/slsa-verifier | unknown_error |
updater | +------------------------------+---------------+
```

**Comment by ianlewis** [comment]
@asraa Is this just a typo? We don't need this for any tests or anything right?

**Comment by asraa** [comment]
Thank you for the info! I'll go ahead and delete all our RC flags, let me know if that'll fix it!
