### ISSUE TITLE
[feature] Verify builder pre-releases

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-verifier#551]
In v2.1.0 tags need to be semantic versions of the form `vX.Y.Z` without metadata.

This means that the verifier can't verify artifacts for pre-releases. We should allow users to verify artifacts on pre-releases somehow. Perhaps via an option if we don't allow it by default.

**Comment by asraa** [comment]
Actually it seems like you mean builder RC's?

**Comment by ianlewis** [comment]
Yeah, sorry. I thought originally this affected artifacts, but it is actually just the builder version check. I still think we should have an option for this, but it's not quite as big an issue.

https://github.com/slsa-framework/slsa-verifier/blob/v2.1.0/verifiers/internal/gha/builder.go#L144-L150
