### ISSUE TITLE
npm attestations file format

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-verifier#563]
The attestations file that npm uploads now is a JSON object rather than a list. slsa-verifier needs to be able to load in this format rather than the previous format which was a simple list.

```shell
$ curl -Ss $(npm view @slsa-framework/e2e-nodejs-tag-main-default-slsa3 --json | jq -r '.dist.attestations.url') | jq | head
{
  "attestations": [
    {
      "predicateType": "https://slsa.dev/provenance/v0.2",
      "bundle": {
        "mediaType": "application/vnd.dev.sigstore.bundle+json;version=0.1",
        "verificationMaterial": {
          "x509CertificateChain": {
            "certificates": [
              {
```

**Comment by laurentsimon** [comment]
I think the assumption is that users would use `curl -s "$attestations_url" | jq -r '.attestations' > "$attestations_file"` to extract the attestations, so nothing has changed from the npm registry. But you proposal improves UX so sounds like a good idea.

**Comment by ianlewis** [comment]
Yeah, I figure it's just better to take the file as downloaded from NPM
