### ISSUE TITLE
[feature][byob] Verification for sha1 provided by TRW for v1.0

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#600]
verification counterpart for https://github.com/slsa-framework/slsa-github-generator/issues/2137

Make sure to follow the comments in https://github.com/slsa-framework/slsa-verifier/issues/599 and differentiate between generators and builders

**Comment by laurentsimon** [comment]
blocked on https://github.com/slsa-framework/slsa-verifier/pull/604 and https://github.com/slsa-framework/slsa-verifier/issues/605

**Comment by ianlewis** [comment]
Blocked on https://github.com/slsa-framework/github-actions-buildtypes/issues/4

**Comment by ianlewis** [comment]
We'll assume the source by normal means for now and worry about the official source designation once it's been decided on.
