### ISSUE TITLE
Support verification for npm SLSA v1.0

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#614]

**Comment by ianlewis** [comment]
What is "npm v1.0"?

**Comment by laurentsimon** [comment]
Updated the title.. I meant npm SLSA v1.0 format

**Comment by laurentsimon** [comment]
npm CLI is close to having support for v1 format https://github.com/npm/cli/pull/6613

**Comment by ramonpetgrave64** [comment]
Duplicate to #450
