### ISSUE TITLE
[docs][byob] Update docs to reflect that --builder-id is not optional for byob

### ISSUE THREAD

**Issue by enteraga6** [slsa-framework/slsa-verifier#656]
If the `--builder-id` flag is not set when using slsa-verifier on a BYOB builder generated provenance and artifact, then the verifier will pick up the delegator as the builder-id.

Documentation should be updated to highlight this caveat for BYOB builders.

Failed SLSA verification when running on BYOB Bazel Builder generated provenance and artifact:

```
FAILED: SLSA verification failed: builderID does not match provenance: expected name 'https://github.com/enteraga6/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml', 
got 'https://github.com/slsa-framework/slsa-github-generator/.github/workflows/delegator_lowperms-generic_slsa3.yml'
exit status 1
```

After including `--builder-id https://github.com/enteraga6/slsa-github-generator/.github/workflows/builder_bazel_slsa3.yml`:

```
Verified build using builder "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/delegator_lowperms-generic_slsa3.yml@refs/tags/v1.7.0" at commit 4684e76a43a096e161631f689ebbe654379e78a5
Verifying artifact ../slsa-github-generator/internal/builders/bazel/test-bin/fib2/fib2: PASSED

PASSED: Verified SLSA provenance
```

**Comment by ianlewis** [comment]
I think we could maybe be a bit nicer to users and provide a friendlier error message if the SAN on the cert is one of the BYOB delegator workflows but `--builder-id` was not provided.

Since BYOB is going to be a framework for tool authors, I'm not sure end users would know what is and isn't a "BYOB" workflow so documenting it as such won't really help much. That's why I think providing an error message telling them that they should specify a `--builder-id` is a better option.

**Comment by laurentsimon** [comment]
> I think we could maybe be a bit nicer to users and provide a friendlier error message if the SAN on the cert is one of the BYOB delegator workflows but `--builder-id` was not provided.
> 
> Since BYOB is going to be a framework for tool authors, I'm not sure end users would know what is and isn't a "BYOB" workflow so documenting it as such won't really help much. 

+1.


What do you think of making the builders hosted on *our* repo *not* require an explicit builder ID? The main reason for requiring builder ID for BYOB is that we expect builders to be on remote repos. But our existing builders don't require the builder ID. So would it make sense to *not* require builder ID for our builders?

**Comment by ianlewis** [comment]
> What do you think of making the builders hosted on _our_ repo _not_ require an explicit builder ID? The main reason for requiring builder ID for BYOB is that we expect builders to be on remote repos. But our existing builders don't require the builder ID. So would it make sense to _not_ require builder ID for our builders?

I don't really have strong opinions either way but I think I'd lean towards being consistent. I hope to move the npm builder out to the npm org one day for example.

**Comment by ianlewis** [comment]
> meaning you're fine then? What I'm proposing is being consistent for builders that are hosted on our org.

Well I meant consistent across BYOB builders but I don't feel strongly either way. I'm ok with not requiring it if it's from the  slsa-github-generator repo.

**Comment by enteraga6** [comment]
That sounds good. We could include a caveat in the BYOB documentation for other developers so that they know. I like the idea of a friendlier, BYOB-specific error message, and +1 to not requiring for slsa-github-generator builders.

**Comment by laurentsimon** [comment]
Closing this issue then. Thanks @enteraga6 for finding this problem! Created https://github.com/slsa-framework/slsa-verifier/issues/659
