### ISSUE TITLE
release.yml: The specified go version file at: go.mod does not exist

### ISSUE THREAD

**Issue by ianlewis** [slsa-framework/slsa-verifier#658]
@asraa noticed an issue with the `release.yml` workflow
https://github.com/slsa-framework/slsa-verifier/pull/643#pullrequestreview-1522248140

The `go-version-file`  go.mod seems to not be found.
https://github.com/slsa-framework/slsa-verifier/actions/runs/5526847990/jobs/10082032703

**Comment by ramonpetgrave64** [comment]
fixed in #697
