### ISSUE TITLE
Make builder ID not compulsory for BYOB builders hosted on our repo

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#659]
See original discussion in https://github.com/slsa-framework/slsa-verifier/issues/656
/cc @enteraga6

**Comment by enteraga6** [comment]
original discussion in #656 and #657

**Comment by laurentsimon** [comment]
Any luck on this feature, @enteraga6 ?

**Comment by enteraga6** [comment]
@laurentsimon writing tests for it, then will pr
