### ISSUE TITLE
feat: Enable granular regression tests

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#709]
Per discussion in https://github.com/slsa-framework/slsa-verifier/issues/707, we'd like to be able to verify certain things end-to-end and need a way to ignore signature verification.

@trishankatdatadog @ianlewis

**Comment by trishankatdatadog** [comment]
> need a way to ignore signature verification.

Or at least use test keys :)

**Comment by trishankatdatadog** [comment]
The more I think about it, I'm increasingly of the opinion that we should _never_ forgo signature verification, even while testing. Better to err on the side of caution and make sure we are always verifying signatures correctly.

**Comment by laurentsimon** [comment]
Indeed, that's one reason I have not built this in the first place. Some things we do is set special env variables and check the identity of the platform it runs on to turn on things like this. Like `"CI": "true"` and `"repository"="slsa-framework/slsa-verifier"` and `"SLSA_VERIFIER_TEST"="1"`. Eg see. https://github.com/slsa-framework/slsa-verifier/blob/f6ae402f458b347d2c414f1d053fc1f8257888d0/verifiers/internal/gha/builder.go#L175-L181 for our end-to-end tests

**Comment by ianlewis** [comment]
Maybe I'm misunderstanding but for regression tests we just need to make sure the thing that used to fail doesn't fail anymore and run the test in an ongoing way to make sure we don't regress. So it should just be a  matter of modifying the digest in the publish attestation JSON and check to make sure the signature validation fails no?

For the regression test the actual digest check shouldn't really come into play (as it's hidden behind the signature check that will fail), and we shouldn't necessarily need to touch the signature I don't think. We can capture tests for behavior here in unit-tests of more granular functions directly with mocks etc.

**Comment by trishankatdatadog** [comment]
> So it should just be a matter of modifying the digest in the publish attestation JSON and check to make sure the signature validation fails no?

Sorry, maybe I didn't sufficiently clarify what I meant: suppose a publish attestation was correctly signed, but for some reason (e.g., a bug or, worse, a key compromise) the subject digest in it did _not_ match the provenance attestation? We should test whether we can catch this, no?

**Comment by ramonpetgrave64** [comment]
@trishankatdatadog Although negative/regression against the NPM subject digests are not in [main_regression_test.go](https://github.com/ramonpetgrave64/slsa-verifier/blob/18c5f13b3ecdf5b79db7448291d3c5aa67683157/cli/slsa-verifier/main_regression_test.go#L1499), the tests you want are done for both the publish and build attestations subject digests in
 - https://github.com/ramonpetgrave64/slsa-verifier/blob/18c5f13b3ecdf5b79db7448291d3c5aa67683157/verifiers/internal/gha/provenance_test.go#L74
 - https://github.com/ramonpetgrave64/slsa-verifier/blob/18c5f13b3ecdf5b79db7448291d3c5aa67683157/verifiers/internal/gha/npm_test.go#L801

And these are both done only after succesfully verifying the signatures on both attestations.
